name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Operating system for the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 
      - name: Install dependencies
        run: npm install
    # - name: Build the project
    #   run: echo "Build the project"
      - name: Run tests
        run: echo "run tests"
